Models/NewsItems.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CricketFavourites.Models
{
    public class NewsItems
    {
        public string _type { get; set; }
        public string readLink { get; set; }
        public int totalEstimatedMatches { get; set; }
        
        [JsonProperty("value")]
        public List<Item> items { get; set; }
    }

    public class Item
    {
        public string _type { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public string description { get; set; }
        public DateTime datePublished { get; set; }
        public string category { get; set; }

    }


}

Controllers/FavouriteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CricketFavourites.Data;
using CricketFavourites.Data.Repositories;
using CricketFavourites.Models;
using CricketFavourites.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;

namespace CricketFavourites.Controllers
{
    [Authorize]
    public class FavouriteController : Controller
    {
        private readonly ICricApiRepository _cricApiRepository;
        private readonly IFavouriteRepository _favouriteRepository;
        private readonly IFileRepository _fileRepository;

        public FavouriteController(ICricApiRepository cricApiRepository, IFavouriteRepository favouriteRepository, IFileRepository fileRepository)
        {
            _cricApiRepository = cricApiRepository;
            _favouriteRepository = favouriteRepository;
            _fileRepository = fileRepository;
        }

        public async Task<IActionResult> ListFavourites()
        {
            var currentFavourites = _favouriteRepository.GetCurrentUserFavourites();
            Dictionary<PlayerInfo, FileModel> combinedPlayerAndImage = new Dictionary<PlayerInfo, FileModel>();
            PlayerInfo currentFavouriteInfo = new PlayerInfo();
            FileModel currentPlayerImage = new FileModel();

            //get up-to-date data on each favourite from the API and add to list
            foreach (var f in currentFavourites)
            {
                currentFavouriteInfo = await _cricApiRepository.GetPlayerInfo(f.Pid);
                currentPlayerImage = _fileRepository.GetImageByFavouriteId(f.Id);
                combinedPlayerAndImage.Add(currentFavouriteInfo, currentPlayerImage);
            }

            return View(new FavouritesViewModel
            {
                CombinedPlayersAndImages = combinedPlayerAndImage
            });
        }

        public IActionResult Search()
        {
            return View();
        }

        [ActionName("SearchWithQuery")]
        public async Task<IActionResult> Search(string query)
        {
            var playerList = await _cricApiRepository.GetPlayers(query);

            return View("Search", new SearchViewModel
            {
                PlayerList = playerList
            });
        }

        [ActionName("PlayerInfoFromPid")]
        public async Task<IActionResult> Search(int pid)
        {
            PlayerInfo selectedPlayerInfo = await _cricApiRepository.GetPlayerInfo(pid);

            return View("Search", new SearchViewModel
            {
                PlayerInfo = selectedPlayerInfo
            });
        }

        public IActionResult AddFavouritePlayer(string fullName, string name, int pid)
        {
            if (_favouriteRepository.HasBeenFavouritedAlready(pid))
            {
                TempData["alreadyFavouritedMessage"] = "You have already favourited this player!";
                return RedirectToAction(nameof(ListFavourites));
            }
            else
            {
                Favourite favourite = new Favourite
                {
                    FullName = fullName,
                    Name = name,
                    Pid = pid
                };

                _favouriteRepository.AddFavourite(favourite);
                return RedirectToAction(nameof(ListFavourites));
            }
        }

        public IActionResult Unfavourite(int pid)
        {
            _favouriteRepository.RemoveFavourite(pid);
            return RedirectToAction(nameof(ListFavourites));
        }

    }
}

Controllers/FileUploadController.cs
using CricketFavourites.Data;
using CricketFavourites.Data.Migrations;
using CricketFavourites.Data.Repositories;
using CricketFavourites.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace CricketFavourites.Controllers
{
    public class FileUploadController : Controller
    {
        private readonly Data.DbContext _dbContext;
        private readonly IFileRepository _fileRepository;
        private readonly IFavouriteRepository _favouriteRepository;

        public FileUploadController(Data.DbContext dbContext, IFileRepository fileRepository, 
            IFavouriteRepository favouriteRepository)
        {
            _dbContext = dbContext;

            _fileRepository = fileRepository;
            _favouriteRepository = favouriteRepository;
        }

        public async Task<IActionResult> Index(int pid)
        {
            if (pid == 0)
            {
                pid = Int32.Parse(TempData["currentPid"].ToString());
            }
            var fileUploadViewModel = await LoadAllFiles();
            fileUploadViewModel.CurrentFavourite = _favouriteRepository.GetFavouriteByPid(pid);
            ViewBag.Message = TempData["Message"];
            TempData["currentPid"] = pid;

            return View(fileUploadViewModel);
        }

        private async Task<FileUploadViewModel> LoadAllFiles()
        {
            var viewModel = new FileUploadViewModel();
            viewModel.Files = await _fileRepository.AllFiles();
            return viewModel;
        }

        public IActionResult SetAsPlayerImage(List<IFormFile> files, int favouriteId)
        {
            _fileRepository.SavePlayerImage(files, favouriteId);
            TempData["Message"] = "File successfully uploaded";
            return RedirectToAction("ListFavourites", "Favourite");
        }
    }
}

Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CricketFavourites.Data.Repositories;
using CricketFavourites.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CricketFavourites.Controllers
{
    [Authorize]
    public class NewsController : Controller
    {
        private readonly INewsApiRepository _newsApiRepository;
        private readonly IFavouriteRepository _favouriteRepository;
        private const int NewsItemsThresholdWhen2FavouritesExist = 2;
        private const int NewsItemsThresholdWhen3OrMoreFavouritesExist = 1;

        public NewsController(INewsApiRepository newsApiRepository, IFavouriteRepository favouriteRepository)
        {
            _newsApiRepository = newsApiRepository;
            _favouriteRepository = favouriteRepository;
        }

        public IActionResult DefaultNewsList()
        {
            List<Favourite> currentUserFavourites = _favouriteRepository.GetCurrentUserFavourites();
            List<string> currentFavouritePlayerNames = new List<string>();
            List<NewsItems> newsItemsList = new List<NewsItems>();

            foreach (Favourite fav in currentUserFavourites)
            {
                currentFavouritePlayerNames.Add(fav.Name);
            }

            bool hasNoFavouritedPlayers = currentUserFavourites.Count == 0;
            bool has1FavouritePlayers = currentUserFavourites.Count == 1;
            bool has2FavouritePlayers = currentUserFavourites.Count == 2;

            if (hasNoFavouritedPlayers)
            {
                TempData["noFavouritesMessage"] = "You have no favourited players. Please search for players and add them to your favourites.";
                return View("NewsList");
            }

            else if (has1FavouritePlayers)
            {
                return RedirectToAction("NewsForSelectedPlayer", new { name = currentFavouritePlayerNames[0] });
            }

            else if (has2FavouritePlayers)
            {
                return RedirectToAction(nameof(ShowNewsFor2Favourites), new { currentFavouritePlayerNames = currentFavouritePlayerNames, newsItemsList = newsItemsList });
            }

            //user has 3 or more favourited players
            else
            {
                return ShowNewsFor3OrMoreFavourites(currentFavouritePlayerNames, newsItemsList);
            }
        }


        public IActionResult NewsForSelectedPlayer(string name)
        {
            var newsItems = _newsApiRepository.GetNews(name);

            TempData["newsPageTitle"] = $"Recent news related to {name}";

            return View("NewsList", newsItems);
        }


        public IActionResult ShowNewsFor2Favourites(List<string> currentFavouritePlayerNames, List<NewsItems> newsItemsList)
        {
            int numberOfFavorites = 2;
            for (int i = 0; i < numberOfFavorites; i++)
            {
                NewsItems newsItems = new NewsItems();
                newsItems = _newsApiRepository.GetNews(currentFavouritePlayerNames[i]);
                newsItemsList.Add(newsItems);
            }

            NewsItems combinedItemsFrom2Players = new NewsItems();
            combinedItemsFrom2Players.items = new List<Item>();

            Dictionary<int, bool> playerHasTwoItems = new Dictionary<int, bool>();
            playerHasTwoItems.Add(0, true);
            playerHasTwoItems.Add(1, true);

            //check that each player actually has at least 2 results
            for (int i = 0; i < numberOfFavorites; i++)
            {
                if (newsItemsList[i].items.Count() < NewsItemsThresholdWhen2FavouritesExist)
                {
                    playerHasTwoItems[i] = false;
                }
            }

            return DisplayNewsDependingOnItemsFrom2Favourites(currentFavouritePlayerNames, newsItemsList, numberOfFavorites, combinedItemsFrom2Players, playerHasTwoItems);
        }

        private IActionResult DisplayNewsDependingOnItemsFrom2Favourites(List<string> currentFavouritePlayerNames, List<NewsItems> newsItemsList, int numberOfFavorites, NewsItems combinedItemsFrom2Players, Dictionary<int, bool> playerHasTwoItems)
        {
            bool notEnoughResultsForEitherPlayer = playerHasTwoItems[0] == false && playerHasTwoItems[1] == false;
            bool onlyPlayer1HasEnoughResults = playerHasTwoItems[0] == true && playerHasTwoItems[1] == false;
            bool onlyPlayer2HasEnoughResults = playerHasTwoItems[0] == false && playerHasTwoItems[1] == true;

            if (notEnoughResultsForEitherPlayer)
            {
                return View("NewsList");
            }

            else if (onlyPlayer1HasEnoughResults)
            {
                return RedirectToAction("NewsForSelectedPlayer", new { name = currentFavouritePlayerNames[0] });
            }

            else if (onlyPlayer2HasEnoughResults)
            {
                return RedirectToAction("NewsForSelectedPlayer", new { name = currentFavouritePlayerNames[1] });
            }

            else //display 2 results for each player
            {
                for (int i = 0; i < numberOfFavorites; i++)
                {
                    for (int j = 0; j < NewsItemsThresholdWhen2FavouritesExist; j++)
                    {
                        combinedItemsFrom2Players.items.Add(newsItemsList[i].items[j]);
                    }
                }

                TempData["newsPageTitle"] = "Recent news related to some of your favourite players";

                return View("NewsList", combinedItemsFrom2Players);
            }
        }

        private IActionResult ShowNewsFor3OrMoreFavourites(List<string> currentFavouritePlayerNames, List<NewsItems> newsItemsList)
        {
            NewsItems newsItems = new NewsItems();
            Dictionary<int, bool> playerHasOneItem = new Dictionary<int, bool>();
            playerHasOneItem.Add(0, true);
            playerHasOneItem.Add(1, true);
            playerHasOneItem.Add(2, true);

            int numberOfFavorites = 3;
            for (int i = 0; i < numberOfFavorites; i++)
            {
                newsItems = _newsApiRepository.GetNews(currentFavouritePlayerNames[i]);
                newsItemsList.Add(newsItems);
            }

            //check that each favourite player has at least 1 news item
            for (int i = 0; i < numberOfFavorites; i++)
            {
                if (newsItemsList[i].items.Count() < NewsItemsThresholdWhen3OrMoreFavouritesExist)
                {
                    playerHasOneItem[i] = false;
                }
            }

            return DisplayNewsDependingOnNewsItemsFrom3Favourites(currentFavouritePlayerNames, newsItemsList, playerHasOneItem, numberOfFavorites);
        }


        private IActionResult DisplayNewsDependingOnNewsItemsFrom3Favourites(List<string> currentFavouritePlayerNames, List<NewsItems> newsItemsList, Dictionary<int, bool> playerHasOneItem, int numberOfFavorites)
        {
            bool noPlayerHasResult = playerHasOneItem[0] == false && playerHasOneItem[1] == false && playerHasOneItem[2] == false;
            bool onlyPlayer1HasResults = playerHasOneItem[0] == true && playerHasOneItem[1] == false && playerHasOneItem[2] == false;
            bool onlyPlayer2HasResults = playerHasOneItem[0] == false && playerHasOneItem[1] == true && playerHasOneItem[2] == false;
            bool onlyPlayer3HasResults = playerHasOneItem[0] == false && playerHasOneItem[1] == false && playerHasOneItem[2] == true;
            bool onlyPlayer1HasNoResults = playerHasOneItem[0] == false && playerHasOneItem[1] == true && playerHasOneItem[2] == true;
            bool onlyPlayer2HasNoResults = playerHasOneItem[0] == true && playerHasOneItem[1] == false && playerHasOneItem[2] == true;
            bool onlyPlayer3HasNoResults = playerHasOneItem[0] == true && playerHasOneItem[1] == true && playerHasOneItem[2] == false;

            if (noPlayerHasResult)
            {
                return View("NewsList");
            }

            else if (onlyPlayer1HasResults)
            {
                return RedirectToAction("NewsForSelectedPlayer", new { name = currentFavouritePlayerNames[0] });
            }

            else if (onlyPlayer2HasResults)
            {
                return RedirectToAction("NewsForSelectedPlayer", new { name = currentFavouritePlayerNames[1] });
            }

            else if (onlyPlayer3HasResults)
            {
                return RedirectToAction("NewsForSelectedPlayer", new { name = currentFavouritePlayerNames[2] });
            }

            else
            {
                return MoreThan1PlayerWithResults(currentFavouritePlayerNames, newsItemsList, numberOfFavorites, onlyPlayer1HasNoResults, onlyPlayer2HasNoResults, onlyPlayer3HasNoResults);
            }
        }


        private IActionResult MoreThan1PlayerWithResults(List<string> currentFavouritePlayerNames, List<NewsItems> newsItemsList, int numberOfFavorites, bool onlyPlayer1HasNoResults, bool onlyPlayer2HasNoResults, bool onlyPlayer3HasNoResults)
        {
            //if two players have at least 1 result, but the 3rd has none, just display results for one of the players who does have some
            if (onlyPlayer3HasNoResults)
            {
                return RedirectToAction("NewsForSelectedPlayer", new { name = currentFavouritePlayerNames[0] });
            }

            else if (onlyPlayer2HasNoResults)
            {
                return RedirectToAction("NewsForSelectedPlayer", new { name = currentFavouritePlayerNames[2] });
            }

            else if (onlyPlayer1HasNoResults)
            {
                return RedirectToAction("NewsForSelectedPlayer", new { name = currentFavouritePlayerNames[1] });
            }


            else
            {
                return threePlayersWithResults(newsItemsList, numberOfFavorites);
            }
        }

Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CricketFavourites.Models;

namespace CricketFavourites.Controllers
{
    public class PageController : Controller
    {
        private readonly ILogger<PageController> _logger;

        public PageController(ILogger<PageController> logger)
        {
            _logger = logger;
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/NewsItem.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Shared/_FavouritePlayer.cshtml
@model KeyValuePair<PlayerInfo, FileModel>


<div class="card">
    @if (Model.Value != null)
    {
        var base64 = Convert.ToBase64String(Model.Value.Data);
        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
        <img class="card-img-top" src="@imgSrc" alt="" />
    }
    else
    {
        <div class="card-img-top">
            <a class="btn btn-primary no-image-button"
               asp-controller="FileUpload"
               asp-action="Index"
               asp-route-pid="@Model.Key.pid">Add an image for this player</a>
        </div>
    }
    <div class="card-body">
        <h3 class="card-subtitle">@Model.Key.name</h3>

        <p>
            <strong>Country:</strong> @Model.Key.country <br />   <strong>Age:</strong> @Model.Key.currentAge <br />  <strong>Batting style:</strong> @Model.Key.battingStyle <br />
            <strong>Bowling style:</strong> @Model.Key.bowlingStyle
        </p>
    </div>
    <div class="card-buttons-container">
            <a class="btn btn-primary"
               asp-controller="News"
               asp-action="NewsForSelectedPlayer"
               asp-route-name="@Model.Key.name">View news</a>
            <a class="btn btn-primary"
               asp-controller="FavouriteStatistics"
               asp-action="ShowPlayerStats"
               asp-route-pid="@Model.Key.pid">Show stats</a>
            <a class="btn btn-primary"
               asp-controller="FavouriteStatistics"
               asp-action="CompareStats"
               asp-route-pid1="@Model.Key.pid">Compare stats with other favourites</a>
            <a class="btn btn-danger"
               asp-action="Unfavourite"
               asp-route-pid="@Model.Key.pid">Unfavourite</a>

        @if (Model.Value != null)
        {
                <a class="btn btn-danger"
                   asp-controller="FileUpload"
                   asp-action="Index"
                   asp-route-pid="@Model.Key.pid">Change image</a>
        }
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CricketFavourites</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://kit.fontawesome.com/94308c0f38.js" crossorigin="anonymous"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark  border-bottom mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Favourite" asp-action="ListFavourites">Cricket Favourites</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="News" asp-action="DefaultNewsList">News</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="FavouriteStatistics" asp-action="CompareStats">Compare Favourites</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Favourite" asp-action="Search">Player Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="page-footer center-on-small-only pt-0">
        <div class="container">
            <!--Grid row-->
            <div class="row pt-5 mb-3 text-center d-flex justify-content-center">
                <!--Grid column-->
                <div class="col-md-2 mb-3">
                    <h6 class="title font-bold"><a asp-controller="Page" asp-action="About">About</a></h6>
                </div>
                <!--Grid column-->
                <!--Grid column-->
                <div class="col-md-2 mb-3">
                    <h6 class="title font-bold"><a asp-controller="Page" asp-action="Contact">Contact</a></h6>
                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

            <hr class="rgba-white-light" style="margin: 0 15%;">

            <!--Grid row-->
            <div class="row d-flex text-center justify-content-center mb-md-0 mb-4">
                <div class="col-md-8 col-12 mt-5">
                    &copy; 2020 - CricketFavourites - Player Information Courtesy of &nbsp;<a href="https://www.cricapi.com/">https://www.cricapi.com/</a>
                    <br />
                    News Courtesy of &nbsp;<a href="https://rapidapi.com/microsoft-azure-org-microsoft-cognitive-services/api/bing-news-search1/details">Bing News Search API</a>

                </div>
            </div>
            <!--Grid row-->
            <hr class="clearfix d-md-none rgba-white-light" style="margin: 10% 15% 5%;">
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>